services:
  db:
    restart: always
    privileged: true
    image: mysql:8.0
    container_name: clinic-mysql
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./db:/var/lib/mysql
      - ./logs/mysql:/logs
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    environment:
      MYSQL_ROOT_PASSWORD: "Abc*(12345)67890"
      MYSQL_USER: "clinic"
      MYSQL_PASSWORD: "Abc$*(12345)67890"
      MYSQL_INITDB_SKIP_TZINFO: "Asia/Shanghai"
    ports:
        - 3306:3306
  server:
    container_name: clinic-server 
    image: clinic
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: clinic
      DB_USERNAME: clinic
      DB_PASSWORD: Abc$*(12345)67890
      SERVER_PORT: 2347
    ports:
      - 2347:2347
      - 3000:3000
      - 5008:5008
  web:
    container_name: clinic-web 
    image: nginx
    restart: always
    depends_on:
      - server
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./init/nginx_http.conf:/etc/nginx/conf.d/default.conf
      - ./web/dist:/usr/share/nginx/html
      - ./logs/server:/app/logs