services:
  db:
    restart: always
    privileged: true
    image: mysql:8.0
    container_name: mysql
    volumes:
      - ./db:/var/lib/mysql
      - ./logs/mysql:/logs
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    environment:
      MYSQL_ROOT_PASSWORD: "Abc*(12345)67890"
      MYSQL_USER: "clinic"
      MYSQL_PASSWORD: "Abc$*(12345)67890"
      MYSQL_INITDB_SKIP_TZINFO: "Asia/Shanghai"
    ports:
        - 3306:3306
    network_mode: "bridge"
  server:
    container_name: server
    image: cuihairu/clinic:v0.1.0
    ports:
      - 2347:2347
    depends_on:
      - db
  web:
    container_name: web 
    image: nginx
    restart: always
    depends_on:
      - server
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./init/nginx_http.conf:/etc/nginx/sites-enabled/default
      - ./web/dist:/usr/share/nginx/html
