spring:
  cache:
    cache-names: cache,customer,treat
    caffeine:
      spec: initialCapacity=50,maximumSize=10000,expireAfterAccess=300s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    dbcp2:
      test-on-borrow: true
      validation-query: SELECT 1
      test-while-idle: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        useUnicode: true
        characterEncoding: UTF-8
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
    open-in-view: false
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days


server:
  port: 2347
  servlet:
    session:
      timeout: 24h

springdoc:
  swagger-ui:
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: true
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.clinic.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
      org.springframework.security: debug