version: '3.4'

services:
  mysql:
    restart: always
    privileged: true
    image: mysql:8.0
    container_name: mysql
    volumes:
      - ./db:/var/lib/mysql
      #- ./conf:/etc/mysql/conf.d
      - ./logs:/logs
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    environment:
      MYSQL_ROOT_PASSWORD: "Abc*(12345)67890"
      MYSQL_USER: "clinic"
      MYSQL_PASSWORD: "Abc$*(12345)67890"
      MYSQL_INITDB_SKIP_TZINFO: "Asia/Shanghai"
    ports:
        - 3306:3306
    network_mode: "bridge"

  clinic:
    image: clinic
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
  nginx:
    container_name: nginx 
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/docker-nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/www:/home/www
      - /home/docker-nginx/log:/var/log/nginx
      - /home/docker-nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /home/docker-nginx/html:/usr/share/nginx/html
